# FLEET CONFIG =================================================================
# RMF Fleet parameters

rmf_fleet:
  name: "deliveryRobot"
  fleet_manager:
    ip: "127.0.0.1"
    port: 22012
    user: "some_user"
    password: "some_password"
  limits:
    linear: [2.5, 0.5] # velocity, acceleration
    angular: [0.5, 0.5] # velocity, acceleration
  profile: # Robot profile is modelled as a circle
    footprint: 1.3 # radius in m
    vicinity: 1.5 # radius in m
  reversible: False # whether robots in this fleet can reverse
  # TODO Update battery parameters with actual specs
  battery_system:
    voltage: 24.0 # V
    capacity: 40.0 # Ahr
    charging_current: 8.8 # A
  mechanical_system:
    mass: 70.0 # kg
    moment_of_inertia: 40.0 #kgm^2
    friction_coefficient: 0.22
  ambient_system:
    power: 100.0 # W
  tool_system:
    power: 0.0 # W
  recharge_threshold: 0.20 # Battery level below which robots in this fleet will not operate
  recharge_soc: 1.0 # Battery level to which robots in this fleet should be charged up to during recharging tasks
  publish_fleet_state: 10.0 # Publish frequency for fleet state, ensure that it is same as robot_state_update_frequency
  account_for_battery_drain: True
  task_capabilities: # Specify the types of RMF Tasks that robots in this fleet are capable of performing
    loop: True
    delivery: True
    clean: False
    finishing_request: "park" # [park, charge, nothing]

# DeliveryRobot CONFIG =================================================================

robots:
  # Here the user is expected to append the configuration for each robot in the
  # fleet.
  # Configuration for deliveryRobot_1
  deliveryRobot_1:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_1_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_1_charger"
  # Configuration for deliveryRobot_2
  deliveryRobot_2:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_2_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_2_charger"

  deliveryRobot_3:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_3_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_3_charger"

  deliveryRobot_4:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_4_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_4_charger"

  deliveryRobot_5:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_5_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_6_charger"


  deliveryRobot_6:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_6_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_6_charger"



  deliveryRobot_7:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_7_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_7_charger"


  deliveryRobot_8:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_8_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_8_charger"


  deliveryRobot_9:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_9_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_9_charger"
  
  deliveryRobot_10:
    robot_config:
      max_delay: 15.0 # allowed seconds of delay of the current itinerary before it gets interrupted and replanned
    rmf_config:
      robot_state_update_frequency: 10.0
      start:
        map_name: "L1"
        waypoint: "deliveryRobot_10_charger"
        orientation: 0.0 # radians
      charger:
        waypoint: "deliveryRobot_10_charger"
